/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the plaky115 SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx spacesListSpaces.example.ts
 */

import { Plaky115 } from "plaky115";

const plaky115 = new Plaky115({
  apiKeyAuth: "<YOUR_API_KEY_HERE>",
});

async function main() {
  const result = await plaky115.spaces.listSpaces({
    expand: [],
  });

  for await (const page of result) {
    console.log(page);
  }
}

main().catch(console.error);
