/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the plaky115-mcp SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx spacesGetSpaces.example.ts
 */

import { Plaky115Mcp } from "plaky115-mcp";

const plaky115Mcp = new Plaky115Mcp({
  apiKeyAuth: "<YOUR_API_KEY_HERE>",
});

async function main() {
  const result = await plaky115Mcp.spaces.getSpaces({
    expand: [],
  });

  console.log(result);
}

main().catch(console.error);
